### PR TITLE
Fixes rails 4.2 compatibility. probably breaks below that though?

### PR DESCRIPTION
**Pull request by kernel-io**
refer to this commit to see what changed with 4.2
https://github.com/rails/rails/commit/4bd5dffc85a4f3a660132eb85806a03fa5904e51

### CODE REVIEW

**Comment by kernel-io** [comment]
thanks travis....

**Comment by dgilperez** [comment]
:+1: ! Any idea on why are tests failing?

**Comment by johncarney** [comment]
Thanks for the PR @kernel-io, if you can get those tests passing I'll merge it.

**Comment by johncarney** [comment]
Scratch that. I'll look into it.

**Comment by kernel-io** [comment]
still looking into it? :)

**Comment by johncarney** [comment]
Yeah, sorry @kernel-io. I've been a bit snowed under lately. Probably won't be able to spend any time on it until sometime next week.

**Comment by kernel-io** [comment]
not a problem at all, my branch is working for me, snowed under as well! :)

**Pull request merged**
