### PR TITLE
Generate attribute methods once instead of on each object creation

### PR DESCRIPTION
**Pull request by monkbroc**
I was investigating memory usage in my app and I found that jc-validates_timeliness created a lot of strings on each request.

It turns out that the attribute methods for timeliness are generated at each object creation instead of once, at first creation like AR attribute methods. Since creating those methods uses `module_eval` it's quite slow when it's done each `Model.new`!

This PR prevents the duplication by following [the same pattern as ActiveRecord](https://github.com/rails/rails/blob/08576b94ad4f19dfc368619d7751e211d23dcad8/activerecord/lib/active_record/attribute_methods.rb#L79).

Benchmark for speed improvement:

```
# rails console
require 'benchmark/ips'
Benchmark.ips do |x|
  x.report("timeliness generated attributes speed") {
    Rental.new # a class in my app that has 3 timeliness validations
  }
end
```

Without patch

```
Calculating -------------------------------------
timeliness generated attributes speed
                       264.000  i/100ms
-------------------------------------------------
timeliness generated attributes speed
                          2.777k (± 5.1%) i/s -     13.992k
```

With patch

```
Calculating -------------------------------------
timeliness generated attributes speed
                       988.000  i/100ms
-------------------------------------------------
timeliness generated attributes speed
                         12.068k (± 4.6%) i/s -     60.268k
```

That's a 4X speed improvement in creating AR objects in my application.

Additionally it names the module to make it easier to see in the ancestor chain.

```
Rental.ancestors
=> [Rental(id: integer, ...),
 Rental::GeneratedValidatesTimelinessMethods, <== instead of #<Module:0x007fc165522078>
 PaperTrail::Model::InstanceMethods,
...
```

### CODE REVIEW

**Comment by monkbroc** [comment]
FYI, the failed tests failed before my patch too. I looks like it has to do with daylight saving time.

**Comment by dgilperez** [comment]
:clap:

I was just doing the same thing, using `derailed_benchmarks`, and saw a large amount of memory required by `jc-validates_timeliness`. Not seeing any difference after your patch though, and the memory is anyway used by `timeliness` dependency.

Also, it seems this fork is no longer maintained. I just switched to https://github.com/appfolio/validates_timeliness, which is currently supporting Rails 4.2 and seems to be quite active. You might send your PR there.

**Comment by monkbroc** [comment]
Thanks for the note @dgilperez. The patch doesn't reduce total allocations, but makes sure that methods are allocated only once instead of on every object creation.

I've been trying to become maintainer of the original gem validates_timeliness in order to pull the different branches back together.

**Comment by dgilperez** [comment]
Great! Please leave a comment here if you manage to merge all those things together.

**Comment by brendon** [comment]
Should this be closed since the PR was merged?

**Comment by monkbroc** [comment]
I don't follow the status of this fork right now so go ahead and close this PR if you think it's right.

**Comment by brendon** [comment]
Thanks @monkbroc, unfortunately I'm not a maintainer :)

In the process of updating my app to Rails 4.2 yesterday I had to take another look at validates_timeliness and I've gotta say, I'm confused about which version to use. There seems to be at least three actively developed versions! Do you have any clues?

**Comment by monkbroc** [comment]
This fork worked ok for me, but I'm sure there are more up to date ones.

**Comment by brendon** [comment]
Thanks @monkbroc. I guess the way forward would be to get an agreement from all existing fork maintainers to redirect all issues and PR's to a new repo. And for that repo to contain a merging of the best bits of each fork. I'm sure it'll happen one day :)

**Pull request closed without merging**
